=== EmanuelePerrone/EmanuelePerrone/5B_Perrone_JSON/ex_1/book-schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "title": {
      "type": "string",
      "minLength": 1
    },
    "authors": {
      "type": "array",
      "items": {
        "type": "string"
      },
      "minItems": 1
    },
    "genre": {
      "type": "string",
      "minLength": 1
    },
    "isbn": {
      "type": "string",
      "pattern": "^(97(8|9))?\\d{9}(\\d|X)$"
    },
    "year_of_publication": {
      "type": "integer",
      "minimum": 1000,
      "maximum": 9999
    },
    "pages": {
      "type": "integer",
      "minimum": 1
    },
    "language": {
      "type": "string",
      "enum": ["it", "en", "fr", "es", "de"]
    }
  },
  "required": ["title", "authors", "genre", "isbn", "year_of_publication", "pages", "language"],
  "additionalProperties": false
}

=== EmanuelePerrone/EmanuelePerrone/5B_Perrone_JSON/ex_1/books-text-data.json
[
    {
      "title": "Il nome della rosa",
      "authors": ["Umberto Eco"],
      "genre": "Mistero",
      "isbn": "9788804370117",
      "year_of_publication": 1980,
      "pages": 502,
      "language": "it"
    },
    {
      "title": "1984",
      "authors": ["George Orwell"],
      "genre": "Dystopia",
      "isbn": "9780451524935",
      "year_of_publication": 1949,
      "pages": 328,
      "language": "en"
    },
    {
      "title": "Le Miserable",
      "authors": ["Victor Hugo"],
      "genre": "Historical Fiction",
      "isbn": "9780199555353",
      "year_of_publication": 1862,
      "pages": 1232,
      "language": "fr"
    },
    {
      "title": "Cien años de soledad",
      "authors": ["Gabriel García Márquez"],
      "genre": "Magical realism",
      "isbn": "9780060883287",
      "year_of_publication": 1967,
      "pages": 417,
      "language": "es"
    },
    {
      "title": "Der Steppenwolf",
      "authors": ["Hermann Hesse"],
      "genre": "Philosophical fiction",
      "isbn": "9780316785554",
      "year_of_publication": 1927,
      "pages": 300,
      "language": "de"
    }
  ]
